# Generated by Django 2.0.6 on 2018-06-27 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20180627_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoursesOffered',
            new_name='Course',
        ),
    ]
