# Generated by Django 2.0.6 on 2018-06-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180627_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(default='', max_length=200),
        ),
    ]
