# Generated by Django 2.0.6 on 2018-06-27 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180627_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='auto_increment_id',
        ),
        migrations.AddField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_offered',
            field=models.ManyToManyField(to='myapp.UserProfile'),
        ),
    ]
