# Generated by Django 2.0.6 on 2018-06-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180627_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_offered',
        ),
    ]
