# Generated by Django 2.0.6 on 2018-06-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_course_course_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_offered',
            field=models.ManyToManyField(to='myapp.UserProfile'),
        ),
    ]
