# Generated by Django 2.0.6 on 2018-06-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_course_course_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='Department',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
