# Generated by Django 2.0.6 on 2018-06-27 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180628_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_offered',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
