# Generated by Django 2.0.6 on 2018-06-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180628_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='department',
            new_name='city',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(default='', max_length=200),
        ),
    ]
