# Generated by Django 2.0.6 on 2018-06-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20180628_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='course',
        ),
    ]
