# Generated by Django 2.0.6 on 2018-06-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20180628_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=100)),
                ('course_offered', models.ManyToManyField(to='myapp.UserProfile')),
            ],
        ),
    ]
