# Generated by Django 2.0.6 on 2018-06-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Department',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_offered',
            new_name='students',
        ),
    ]
