# Generated by Django 2.0.6 on 2018-06-27 20:06

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20180628_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='', max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
    ]
