# Generated by Django 2.0.6 on 2018-06-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20180628_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
